# Lab 2: Observability and Evaluation

A customer asks: **“Can I return these headphones?”** We will follow that one question from the Bedrock call to its trace, cost, and quality check.

**Observability** explains what happened: which operations ran, how long they took, and how many tokens they used. **Evaluation** asks whether the answer met the customer's requirements. A fast, cheap answer can still be wrong.

Run one code cell at a time. The **Check** notes tell you what to look for in each result. You will first generate an answer to the customer's question, then use AgentCore Evaluation to assess whether that answer follows the return policy.

| Step | You will do | Look for |
|---|---|---|
| Prepare | Select the model and start telemetry | The model and backend you intended |
| Ask | Send one support question | An answer that keeps the packaging requirement |
| Inspect | Read its local trace tree | Two observation layers, one model invocation |
| Open | Find the same request in CloudWatch | Matching trace and session IDs |
| Measure | Reconcile tokens and estimate cost | One model-call receipt, without double counting |
| Evaluate | Check the recorded answer | A score **and** a useful explanation |
| Continue | Send the customer's follow-up question | A new trace in the same session |

By the end, you should be able to explain a trace, find it in the backend, and apply the same instrumentation pattern to your own application.

## Prepare: start with a fresh kernel

Complete [Jupyter setup](00-jupyter-notebook-101.ipynb) and [Prompts 101](01-prompts-101.ipynb). Select **Bedrock Workshop (Python 3.13)** and restart the kernel. Tracing must be initialized before the application client it observes.

The environment already has the notebook dependencies and AWS telemetry destination. You will use the model and backend selected below; the **Bring this to your own project** section explains the equivalent setup outside the workshop.

### Check the environment

Run the next cell to confirm the Python kernel and installed SDKs. If the kernel check fails, select the workshop kernel before continuing.

In [1]:
import sys
from importlib.metadata import version
from pathlib import Path

if sys.version_info[:2] != (3, 13):
    raise RuntimeError("Select Bedrock Workshop (Python 3.13), then restart the kernel.")

REPO = next(
    (p for p in (Path.cwd(), *Path.cwd().parents)
     if (p / "pyproject.toml").is_file() and (p / "workshop_utils").is_dir()),
    None,
)
if REPO is None:
    raise RuntimeError("Open this notebook inside the workshop repository.")

print("Kernel:", sys.executable)
print("Python:", sys.version.split()[0])
print({name: version(name) for name in ("boto3", "botocore", "bedrock-agentcore")})
import workshop_utils

print("Shared package:", workshop_utils.__file__)

Kernel: /workshop/.venv/bin/python
Python: 3.13.15
{'boto3': '1.43.101', 'botocore': '1.43.101', 'bedrock-agentcore': '1.23.1'}
Shared package: /workshop/workshop_utils/__init__.py

### Check Bedrock access and select the model

The next cell checks model access and selects **Sonnet 5** for this lab, or **Sonnet 4.6** if Sonnet 5 is unavailable. It also checks **Haiku 4.5**, the workshop's smaller-model option. The output shows the selected models.

In [2]:
import json
import os
import time
from uuid import uuid4

import boto3
from botocore.config import Config
from dotenv import load_dotenv
from IPython.display import display

from workshop_utils.models import Support
from workshop_utils.pacing import attach_boto3, get_workshop_pacer
from workshop_utils.preflight import preflight_models
from workshop_utils.pricing import get_price

load_dotenv(REPO / ".env", override=False)
REGION = "us-east-1"
# Explicit setup I/O: STS identity plus small billable probes on cache misses.
# Probe attempts are setup overhead and are not baseline usage or latency.
REFRESH_PREFLIGHT = False  # After permission changes, restart and set True for a new experiment.
PREFLIGHT_CACHE = REPO / ".models.json"
model_override = os.getenv("WORKSHOP_MODEL_ID") or None
probe_runtime = boto3.client(
    "bedrock-runtime", region_name=REGION,
    config=Config(connect_timeout=5, read_timeout=90, retries={"total_max_attempts": 1}),
)
attach_boto3(probe_runtime, get_workshop_pacer())
probe_sts = boto3.client(
    "sts", region_name=REGION,
    config=Config(connect_timeout=5, read_timeout=10, retries={"total_max_attempts": 1}),
)
try:
    PREFLIGHT = preflight_models(
        probe_runtime, sts_client=probe_sts, region=REGION,
        overrides={"workhorse": model_override} if model_override else None,
        cache_path=PREFLIGHT_CACHE, refresh=REFRESH_PREFLIGHT,
    )
finally:
    probe_runtime.close()
    probe_sts.close()

SELECTED = PREFLIGHT.models["workhorse"]
MODEL_ID = SELECTED.model_id
EFFORT = "low" if SELECTED.capabilities.support("effort") is Support.SUPPORTED else None
PREFLIGHT_REPORT = PREFLIGHT.as_dict()
for role, model in PREFLIGHT.models.items():
    print(f"{role.capitalize()} role OK: {model.model_id}")
cached_probes = sum(item["cache_hit"] for item in PREFLIGHT_REPORT["probes"])
print(f"Probe evidence: {cached_probes} cached; "
      f"{len(PREFLIGHT_REPORT['probes']) - cached_probes} new attempts.")
for item in PREFLIGHT_REPORT["probes"]:
    if item["status"] == "unavailable":
        print(f"Fallback: {item['model_id']} unavailable; selected {MODEL_ID}.")

price = get_price(SELECTED)
MANIFEST = {
    **SELECTED.as_dict(), "effort": EFFORT, "service_tier": "standard",
    "prompt_version": "return-policy-v1", "dataset_version": "return-policy-smoke-v1",
    "pricing_date": price.verified_on, "price_evidence": price.evidence,
    "tools": [], "knowledge_base": None, "setup_preflight": PREFLIGHT_REPORT,
}
print(f"Experiment ready: {REGION}, {EFFORT or 'default'} effort. Full details: MANIFEST.")

Workhorse role OK: global.anthropic.claude-sonnet-5
Small role OK: global.anthropic.claude-haiku-4-5-20251001-v1:0
Probe evidence: 2 cached; 0 new attempts.
Experiment ready: us-east-1, low effort. Full details: MANIFEST.

## 1. Start recording before making the request

To understand what happened during a model request, we collect **telemetry**: records of its timing, token usage, errors, and other details.

- **Instrumentation** is the code that records these details as the application runs. For a model call, it can record when the call starts, when it finishes, and which model was used. You can add this code yourself or use a library that records supported calls automatically.
- **OpenTelemetry (OTel)** is an open-source set of standards and tools for collecting telemetry in a common format. It represents a timed operation, such as a model call, as a **span**. Related spans form a **trace**, showing the steps within a request.
- **AWS Distro for OpenTelemetry (ADOT)** is AWS's supported distribution of OpenTelemetry. In this notebook, it sets up Python instrumentation and exports the recorded telemetry to CloudWatch, where you can search and inspect it.

<img src="images/observability-flow.png" alt="The same model call is observed locally and exported to CloudWatch" width="850">

The next cell calls `setup_observability`. In this notebook it:

1. Labels telemetry with the service name `fundamentals-notebook`.
2. Checks the configured log stream, then initializes ADOT for the AWS destination.
3. Instruments SDK operations and adds an in-memory collector so we can inspect finished spans immediately.
4. Adds the Langfuse exporter when `langfuse` or `both` is selected.

It does not call the model or deploy an agent. `agentcore` is the workshop's name for the AWS export configuration. The local collector is a teaching aid; CloudWatch is the persistent, searchable backend.

The same provider remains active for this Python process. Restart the kernel to change its backend. The **Bring this to your own project** section below shows the standard environment variables and launch command behind this convenience helper.

**Check:** the next output should name your chosen backend, service and Region.

In [3]:
import os

from dotenv import load_dotenv

from workshop_utils.observability import resolve_notebook_backend, setup_observability

load_dotenv(REPO / ".env", override=False)
REGION = "us-east-1"
BACKEND = resolve_notebook_backend(REPO / ".env")
if BACKEND == "none":
    raise ValueError("This tracing lab needs agentcore, or an explicitly configured optional backend.")
telemetry = setup_observability(
    BACKEND, service_name="fundamentals-notebook", region=REGION,
    max_spans=2048,
)
LOG_GROUP = telemetry.log_group  # Custom logs/metrics group from the canonical environment/default.
TRACE_LOG_GROUP = "aws/spans"
print(f"Telemetry ready: {telemetry.backend} | {telemetry.service_name} | {REGION}")
if BACKEND in {"agentcore", "both"}:
    print(f"Trace store: {TRACE_LOG_GROUP}; application logs/metrics: {LOG_GROUP}")

2026-10-21 06:46:08,675 WARNING [opentelemetry.instrumentation.logging] [__init__.py:234] [trace_id=0 span_id=0 resource.service.name=fundamentals-notebook trace_sampled=False] - Skipping installation of LoggingHandler from `opentelemetry-instrumentation-logging` to avoid duplicate logs. The SDK's deprecated LoggingHandler is already active (OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true). To migrate, unset this environment variable. The SDK's handler will be removed in a future release.

Telemetry ready: both | fundamentals-notebook | us-east-1
Trace store: aws/spans; application logs/metrics: /aws/bedrock-agentcore/workshop/notebook-agents

### Session, trace, and span

Imagine a customer having a conversation with your support assistant. We use three levels to organize the records of what the application does:

| Term | What it represents | Example |
|---|---|---|
| **Session** | The conversation, grouping the customer's related questions and the assistant's answers. | The whole conversation about returning a pair of headphones. |
| **Trace** | The record of the work done to answer **one question**, from receiving it to returning an answer. | Everything the application does to answer “Can I return these headphones?” |
| **Span** | The record of **one operation within a trace**, including its start time, duration, and details. | A model call, a policy lookup, or a tool call used to prepare that answer. |

A trace can contain several spans if answering one question takes several steps. Each span has its own ID; spans belonging to the same request share a trace ID.

#### Why does one conversation have two traces?

1. The customer asks **“Can I return these headphones?”** The application handles that question and returns an answer. That work is recorded in **Trace A**.
2. The customer then asks **“What if I no longer have the original packaging?”** The application handles this new question and returns another answer. That work is recorded in **Trace B**.

Both traces share the same **session ID** because they belong to the same conversation. They have different **trace IDs** because each question starts a new request.

<img src="images/trace-session-spans.png" alt="One headphones-return conversation contains Trace A for the first question and Trace B for the follow-up; each trace contains nested application and model-call spans" width="850">

**In this notebook, you create Trace A first.** Section 6 continues the conversation and creates Trace B.

#### Why are there two spans inside each trace?

This lab records the same request at two levels:

- The **blue application span** records the question and answer in the context of the conversation.
- The **purple model-call span** records the Bedrock API call made inside that operation.

The purple span's `parentSpanId` points to the blue span, showing that it belongs inside it. There is only **one model call per question** in this example. The two spans do not mean the model answered twice; later, we will use the model-call record when counting tokens and estimating cost.

### Create the Bedrock client

A **Bedrock client** is the Python object your code uses to send requests to Bedrock. We name it `runtime`, so a call such as `runtime.converse(...)` sends a prompt to the model.

We enabled ADOT earlier. Creating the client now lets ADOT's instrumentation record its model calls as spans, including their timing and usage. Follow this order:

**Enable tracing → create the client → send the request.**

Run the next cell to create `runtime`. The message **Bedrock client ready** confirms the client has been created. You'll use it to send the customer's question in the next step.

In [4]:
import pandas as pd

from workshop_utils.bedrock import NormalizedUsage, build_converse_request, normalize_usage
from workshop_utils.evals import quick_eval
from workshop_utils.metrics import metrics_records
from workshop_utils.observability import converse_observation, response_span
from workshop_utils.pacing import attach_boto3, get_workshop_pacer
from workshop_utils.pricing import (
    AmbiguousCacheUsageError,
    InferredPriceError,
    UnknownPriceError,
    calculate_cost,
)

# A fresh application client is created after ADOT initialization.
# SELECTED was already resolved by the explicit preflight, not by offline ordering.
runtime = boto3.client(
    "bedrock-runtime", region_name=REGION,
    config=Config(connect_timeout=5, read_timeout=90, retries={"total_max_attempts": 1}),
)
attach_boto3(runtime, get_workshop_pacer())
print(f"Bedrock client ready in {REGION}. The next cell sends the support question.")

Bedrock client ready in us-east-1. The next cell sends the support question.

## 2. Ask the support question

Now send the customer's question to the model, along with TechMart's return policy. The policy has three requirements:

| Return requirement | What the customer has told us |
|---|---|
| Purchase within 30 days | Bought the headphones 14 days ago |
| Receipt available | Has a receipt |
| Original packaging available | Not yet confirmed |

The answer should explain that the customer also needs the original packaging.

In the next cell:

- `runtime.converse(...)` sends the prompt and receives the model's answer.
- The surrounding `with converse_observation(...)` block records the call as an application span, so you can inspect it afterwards.

`EXPECTED` is a reference answer: an example of what a correct response should include. We will compare the model's answer with it in the evaluation step.

**Try it:** run the cell and read the answer. Does it mention the original packaging requirement? The output also shows the trace ID and session ID, which you'll use to find this request in CloudWatch.

In [5]:
POLICY = "TechMart accepts headphone returns within 30 days with a receipt and original packaging."
QUESTION = "I bought headphones 14 days ago and have a receipt. Can I return them?"
EXPECTED = "Yes, the purchase is within 30 days and you have a receipt; original packaging is also required."
SESSION_ID = f"fundamentals-{uuid4().hex}"
request = build_converse_request(
    SELECTED,
    [{"role": "user", "content": [{"text": QUESTION}]}],
    system=[{"text": (
        "You are a TechMart support assistant. Answer using only the policy in at most two sentences. "
        "State any requirement the customer has not confirmed. Policy: " + POLICY
    )}],
    max_tokens=512, effort=EFFORT,
)
# Clear local setup capture, then measure only this new application session/trace.
# Setup probes and their charges remain outside baseline measurements.
telemetry.collector.clear()
start_ns = time.time_ns()
start_clock = time.perf_counter()
with converse_observation(request, session_id=SESSION_ID) as record_response:
    response = runtime.converse(**request)
    response = record_response(response)
client_e2e_ms = (time.perf_counter() - start_clock) * 1000
end_ns = time.time_ns()
answer = "".join(block["text"] for block in response["output"]["message"]["content"] if "text" in block)
TRACE_ID = response["_trace"]["trace_id"]
SPAN_ID = response["_trace"]["span_id"]
print(answer)
print("Stop reason:", response["stopReason"])
print("Trace ID:", TRACE_ID)
print("Session ID:", SESSION_ID)
print("Client end-to-end ms:", round(client_e2e_ms, 1))

2026-10-21 06:46:09,276 INFO [botocore.credentials] [credentials.py:1171] [trace_id=0 span_id=0 resource.service.name=fundamentals-notebook trace_sampled=False] - Found credentials from IAM Role: code-editor-CodeEditorInstanceBootstrapRole-rqoMyTLbiTaA

Yes, you're within the 30-day window and have a receipt—but you haven't confirmed you still have the original packaging, which is also required for the return.
Stop reason: end_turn
Trace ID: 823c82466ca1a526266e9d9fe3e3da70
Session ID: fundamentals-d74d6d95128550aa79ab784c9dea0482
Client end-to-end ms: 1896.6

### Read the local trace tree

A **trace tree** shows which operations happened inside other operations. The next cell displays the spans recorded for your question as a table. For the AWS tracing setup, look for these two rows:

| Step | What it records | How it fits in the tree |
|---|---|---|
| **Application wrapper** | The request recorded by the `with converse_observation(...)` block. | The **root**: the top-level span for this request. |
| **Bedrock SDK call** | The `runtime.converse(...)` call made inside that block. | A **child** of the application span. |

**Try it:** run the cell, then follow the connection:

1. Find **Application wrapper**. Its **Parent span** column says `Root`, meaning it has no parent in this trace.
2. Find **Bedrock SDK call**. Its **Parent span** should match the application's **Span ID**. This tells you the model call happened inside the application span.

The **Duration (ms)** column shows how long each operation took. The model-call duration is already included in the application duration, so these times overlap. The two rows describe **one model call**.

**Local** means these records were collected in the notebook and can be inspected immediately. Next, you'll find the same trace in CloudWatch using its trace ID.

In [6]:
call_spans = [
    doc for doc in telemetry.collector.span_documents()
    if doc.get("traceId") == TRACE_ID
]
trace_rows = []
for doc in call_spans:
    if "startTimeUnixNano" not in doc:
        continue
    scope = doc.get("scope", {}).get("name", "")
    step = ("Application wrapper" if scope.endswith("workshop_converse")
            else "Bedrock SDK call" if "botocore" in scope else doc.get("name", "Operation"))
    trace_rows.append({
        "Step": step, "Span ID": doc["spanId"],
        "Parent span": doc.get("parentSpanId") or "Root",
        "Duration (ms)": round((doc["endTimeUnixNano"] - doc["startTimeUnixNano"]) / 1e6, 1),
    })
display(pd.DataFrame(trace_rows).sort_values("Parent span", key=lambda col: col != "Root").reset_index(drop=True))
print("Full span details are available in call_spans.")

                  Step           Span ID       Parent span  Duration (ms)
0  Application wrapper  befd9ed86980227a              Root         1896.3
1     Bedrock SDK call  6ccaa065afb9155c  befd9ed86980227a         1894.4

Full span details are available in call_spans.

## 3. Find this request in CloudWatch

You've seen the trace inside the notebook. Now open the same request in **CloudWatch GenAI Observability**, where you can search across requests and inspect their details.

The next cell sends any recorded telemetry still waiting to be exported. It then prints the service name, session ID, trace ID, and a link directly to your trace within its CloudWatch session.

**To find your request:**

1. Run the cell and click **Open this trace in CloudWatch**. The link includes your Region, service name, session ID, and trace ID.
2. Expand the spans in the selected trace and open the Bedrock model call.

| What to inspect | What to compare with the notebook |
|---|---|
| **Prompt and answer** | The customer's question, supplied policy, and generated answer. |
| **Token usage** | The input and output token counts returned by the model. |
| **Duration** | How long the model call took. |

<img src="images/cloudwatch-agentcore-overview.png" alt="CloudWatch AgentCore overview showing session, trace and error metrics" width="900">

*Example [AgentCore overview](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/agent-view.html). Your dashboard shows data from your own requests.*

<img src="images/cloudwatch-agentcore-sessions.png" alt="CloudWatch Sessions view, where participants can find their printed session ID and open its traces" width="900">

*Example [Sessions view](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/session-view.html), where you can also browse conversations. The notebook link opens your session with the trace selected.*

If the request is not visible yet, allow a few minutes for CloudWatch to receive it, then refresh and check the time range again.

If you selected the Langfuse-only backend, follow the Langfuse section below to find the trace in your project.

In [7]:
from urllib.parse import quote, urlencode

from IPython.display import Markdown

flushed = telemetry.flush(timeout_ms=5000)
print("Pending telemetry flushed." if flushed else "Flush did not finish; retry before checking the backend.")
print("Service:", telemetry.service_name)
print("Session ID:", SESSION_ID)
print("Trace ID:", TRACE_ID)
if BACKEND in {"agentcore", "both"}:
    session_query = urlencode({
        "serviceName": telemetry.service_name, "source": "agents", "traceId": TRACE_ID,
    })
    CLOUDWATCH_URL = (
        f"https://{REGION}.console.aws.amazon.com/cloudwatch/home?region={REGION}"
        f"#gen-ai-observability/agent-core/agent/{quote(telemetry.service_name, safe='')}"
        f"/session/{quote(SESSION_ID, safe='')}?{session_query}"
    )
    display(Markdown(f"[Open this trace in CloudWatch]({CLOUDWATCH_URL})"))
    print("Expand the selected trace to inspect the Bedrock model call.")
else:
    print("This run exports to Langfuse only. Open your project and search for the trace ID above.")

2026-10-21 06:46:11,091 INFO [botocore.credentials] [credentials.py:1171] [trace_id=0 span_id=0 resource.service.name=fundamentals-notebook trace_sampled=False] - Found credentials from IAM Role: code-editor-CodeEditorInstanceBootstrapRole-rqoMyTLbiTaA

Pending telemetry flushed.
Service: fundamentals-notebook
Session ID: fundamentals-d74d6d95128550aa79ab784c9dea0482
Trace ID: 823c82466ca1a526266e9d9fe3e3da70

[Open this trace in CloudWatch](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#gen-ai-observability/agent-core/agent/fundamentals-notebook/session/fundamentals-d74d6d95128550aa79ab784c9dea0482?serviceName=fundamentals-notebook&source=agents&traceId=823c82466ca1a526266e9d9fe3e3da70)

Expand the selected trace to inspect the Bedrock model call.

## 4. Read the request's token and cost receipt

The next cell uses the recorded trace to summarize the resources used to answer the customer's question. Think of the result as a receipt for that model call.

| Measurement | What it tells you |
|---|---|
| **Model calls** | How many times the model was called to answer the question. |
| **Model/profile** | Which model handled the request. |
| **Uncached input tokens** | Prompt tokens processed without reusing cached input. |
| **Output tokens** | Tokens generated by the model. |
| **Cache-read / cache-write tokens** | Input tokens reused from a cache or stored for later reuse. |
| **Estimated model cost (USD)** | The estimated charge for those tokens, using the selected model's prices. |
| **Caller duration (ms)** | How long the notebook waited for the answer. |

The earlier trace table had an application span and a model-call span. Both describe the same request, so this summary counts the model call and its tokens **once**.

**Try it:** run the cell and confirm that **Model calls = 1**. Then read the input tokens, output tokens, and estimated cost for your answer. If the cost shows **Not priced**, the calculator could not determine an estimate from the available pricing information.

In [8]:
def price_observed_call(*, model_id, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens):
    usage = NormalizedUsage(input_tokens, output_tokens, cache_read_tokens, cache_write_tokens)
    try:
        return calculate_cost(model_id, usage, region=REGION).total_cost
    except (UnknownPriceError, InferredPriceError, AmbiguousCacheUsageError):
        return None

records = metrics_records(call_spans, backend="memory", pricing=price_observed_call)
if len(records) != 1:
    raise RuntimeError("Expected one attributed model call. Inspect scope and parent IDs before trusting totals.")

receipt = records[0]
display(pd.DataFrame([
    ("Model calls", len(records)),
    ("Model/profile", receipt["model_id"]),
    ("Uncached input tokens", receipt["input_tokens"]),
    ("Output tokens", receipt["output_tokens"]),
    ("Cache-read tokens", receipt["cache_read_tokens"]),
    ("Cache-write tokens", receipt["cache_write_tokens"]),
    ("Estimated model cost (USD)", f"{receipt['cost_usd']:.6f}" if receipt["cost_usd"] is not None else "Not priced"),
    ("Caller duration (ms)", round(client_e2e_ms, 1)),
], columns=["Measurement", "This request"]))

                  Measurement                      This request
0                 Model calls                                 1
1               Model/profile  global.anthropic.claude-sonnet-5
2       Uncached input tokens                               107
3               Output tokens                                48
4           Cache-read tokens                                 0
5          Cache-write tokens                                 0
6  Estimated model cost (USD)                          0.000694
7        Caller duration (ms)                            1896.6

### Check the receipt against the model response

Bedrock returns token counts with the model's answer. Our tracing also records those counts. Comparing the two helps confirm that the trace captured the usage correctly.

The next cell displays four rows: input tokens, output tokens, cache-read tokens, and cache-write tokens. Each row has two columns:

| Column | Where the count comes from |
|---|---|
| **response** | The usage returned directly by Bedrock with the answer. |
| **span** | The usage recorded in the trace and used for the cost receipt. |

**Try it:** run the cell and compare the numbers across each row. The two columns should match. If they do, the cell prints a confirmation; if they differ, it stops with a usage-mismatch error so you can investigate before relying on the cost estimate.

The receipt estimates the cost of this model call. The evaluation step later has its own cost.

In [9]:
raw_usage = normalize_usage(response["usage"], source="converse")
comparison = {
    name: {"response": getattr(raw_usage, name), "span": records[0][name]}
    for name in ("input_tokens", "output_tokens", "cache_read_tokens", "cache_write_tokens")
}
display(pd.DataFrame.from_dict(comparison, orient="index").rename_axis("Token meter").reset_index())
assert all(values["response"] == values["span"] for values in comparison.values()), "Usage mismatch"
assert records[0]["ttft_ms"] is None, "Non-streaming Converse must not fabricate TTFT"
print("Token meters reconciled for this observed call.")

          Token meter  response  span
0        input_tokens       107   107
1       output_tokens        48    48
2   cache_read_tokens         0     0
3  cache_write_tokens         0     0

Token meters reconciled for this observed call.

### Optional: check CloudWatch records from Python

You can also check your trace using Python. This is useful when you want an automated check that your application's telemetry reached CloudWatch correctly.

The next cell:

1. Reads the recorded spans from CloudWatch for your session and trace.
2. Matches their IDs to the spans collected in the notebook.
3. Compares the input, output, cache-read, and cache-write token counts.

**To try it:** set `RUN_CLOUDWATCH_READBACK = True` and run the cell. This uses the AWS tracing backend (`agentcore` or `both`) and checks the request you already recorded. It may wait up to five minutes for the trace to appear in CloudWatch.

**What to look for:** `Backend check passed` means the IDs and token counts match. If the records cannot be retrieved, the output reports that the check is incomplete. A mismatch stops the cell with an error identifying what differs.

In [10]:
from datetime import UTC, datetime, timezone

from workshop_utils.evals import IncompleteTracesError, SpanCollectionError, collect_runtime_spans

RUN_CLOUDWATCH_READBACK = False
if RUN_CLOUDWATCH_READBACK and BACKEND in {"agentcore", "both"}:
    logs_client = boto3.client(
        "logs", region_name=REGION,
        config=Config(connect_timeout=2, read_timeout=5, retries={"total_max_attempts": 1}),
    )
    expected_ids = sorted({doc["spanId"] for doc in call_spans if "startTimeUnixNano" in doc})
    try:
        exported_spans = collect_runtime_spans(
            client=logs_client, session_id=SESSION_ID,
            expected_span_ids={TRACE_ID: expected_ids}, log_groups=list(dict.fromkeys([TRACE_LOG_GROUP, LOG_GROUP])),
            start_time=datetime.fromtimestamp(start_ns / 1e9, UTC),
            end_time=datetime.fromtimestamp(end_ns / 1e9, UTC),
            timeout_s=300, poll_interval_s=5,
        )
    except (IncompleteTracesError, SpanCollectionError) as exc:
        print("CloudWatch readback not complete:", exc)
    else:
        cloudwatch_records = metrics_records(exported_spans, backend="cloudwatch", pricing=price_observed_call)
        local_by_id = {(row["trace_id"], row["span_id"]): row for row in records}
        remote_by_id = {(row["trace_id"], row["span_id"]): row for row in cloudwatch_records}
        assert local_by_id.keys() == remote_by_id.keys(), "Model-call identity mismatch"
        for key in local_by_id:
            for meter in ("input_tokens", "output_tokens", "cache_read_tokens", "cache_write_tokens"):
                assert local_by_id[key][meter] == remote_by_id[key][meter], f"Mismatch: {key}, {meter}"
        print(f"Backend check passed: {len(cloudwatch_records)} model call; IDs and all token meters match.")
else:
    print("CloudWatch readback skipped; no delivery claim.")

Backend check passed: 1 model call; IDs and all token meters match.

## 5. Evaluate the answer

So far, you've inspected how long the request took and how many tokens it used. Now check whether the answer follows the return policy.

For this evaluation, we use three pieces of information:

| Input | What it contains |
|---|---|
| **Customer question — `QUESTION`** | The customer bought headphones 14 days ago, has a receipt, and wants to return them. |
| **Model answer — `answer`** | The actual response generated earlier in this notebook. |
| **Reference answer — `EXPECTED`** | An example of a correct response: the purchase is within 30 days, the customer has a receipt, and original packaging is also required. |

The model's answer can use different wording from the reference. What matters is whether it gives the correct information, including the packaging requirement.

The next cell puts the question and recorded answer into `qa_document`, ready to send for evaluation. It keeps the trace ID so the evaluation can be linked to the request you inspected.

**Try it:** run the cell and read the printed reference answer. Compare it with the model's answer before asking the evaluator to score it.

In [11]:
qa_document = response_span(
    QUESTION, answer,
    session_id=SESSION_ID, trace_id=TRACE_ID, span_id=SPAN_ID,
    start_time_ns=start_ns, end_time_ns=end_ns,
    service_name="fundamentals-notebook",
)
print("Evaluation input ready for trace:", TRACE_ID)
print("Reference answer:", EXPECTED)
# This creates a document only; it does not export an additional span.

Evaluation input ready for trace: 823c82466ca1a526266e9d9fe3e3da70
Reference answer: Yes, the purchase is within 30 days and you have a receipt; original packaging is also required.

### Run the correctness evaluation

**[AgentCore Evaluations](https://docs.aws.amazon.com/bedrock-agentcore/latest/devguide/evaluations.html)** can assess recorded responses using built-in evaluators. This lab uses **`Builtin.Correctness`**, which checks whether the answer is correct using the question and the supplied reference answer.

This uses an **LLM as a judge**: a model assesses the recorded answer and explains its assessment. It can recognize correct answers even when their wording differs from the reference.

**To run it:** execute the next cell. It submits the prepared answer and reference to AgentCore for an **on-demand evaluation**, meaning the check runs when you request it. Evaluation has its own charge.

| Output | How to read it |
|---|---|
| **Score and label** | The evaluator's assessment of the answer's correctness. |
| **Explanation** | Why it gave that assessment, including any missing or incorrect information. |
| **Evaluator token usage** | Tokens used to perform the assessment, when returned. |
| **Evaluation duration** | How long the assessment took. |

**What to look for:** does the explanation agree with your reading of the answer? In particular, does it account for the original packaging requirement? Review the explanation alongside the answer and reference; an evaluator can also make mistakes.

In [12]:
# One billed evaluator call when you execute this cell; no application inference.
evaluation_client = boto3.client(
    "bedrock-agentcore", region_name=REGION,
    config=Config(connect_timeout=5, read_timeout=90, retries={"total_max_attempts": 1}),
)
evaluation_started = time.perf_counter()
evaluation_results = quick_eval(
    [qa_document], client=evaluation_client, evaluator_id="Builtin.Correctness",
    session_id=SESSION_ID, trace_ids=[TRACE_ID], ground_truth={TRACE_ID: EXPECTED},
)
evaluation_elapsed_s = time.perf_counter() - evaluation_started
for result in evaluation_results:
    print(f"Evaluator: {result['evaluatorId']}")
    print(f"Score: {result.get('value')} | Label: {result.get('label')}")
    print("Explanation:", result.get("explanation", "No explanation returned."))
    if result.get("tokenUsage"):
        print("Evaluator token usage (separate from the application):", result["tokenUsage"])
    print()
print(f"Observed evaluator duration: {evaluation_elapsed_s:.2f} seconds")

Evaluator: Builtin.Correctness
Score: 1.0 | Label: Correct
Explanation: The agent response conveys the same core factual content as the expected response: (1) the purchase is within the 30-day return window, (2) the customer has a receipt, and (3) original packaging is also required. The agent adds a slight nuance by noting the customer hasn't confirmed they have the original packaging, but this is consistent with the expected response's message that original packaging is required. The core information matches.
Evaluator token usage (separate from the application): {'inputTokens': 544, 'outputTokens': 112, 'totalTokens': 656}

Observed evaluator duration: 1.82 seconds

## 6. Follow the next conversation turn

Continue the conversation to see how a follow-up question creates a **new trace within the same session**.

The customer now asks:

> What if I no longer have the original packaging?

The first question left packaging unconfirmed. This follow-up confirms it is missing, so the answer should explain that the standard return policy requires it.

The next cell sends the conversation so far in this order:

| Message | Content |
|---|---|
| **First customer message** | The original question about returning the headphones. |
| **Assistant message** | The answer the model already generated. |
| **New customer message** | The follow-up about missing packaging. |

Including the earlier messages gives the model context for its answer. Reusing the session ID groups the two requests together in the trace viewer.

**Try it:** run the next cell to send the follow-up question. This makes one additional model request.

**What to look for:**

- **Answer:** does it account for the missing packaging?
- **Same session:** the session ID stays the same because the conversation continues.
- **First trace / Follow-up trace:** the IDs differ because these are two separate requests.

Click **Open the follow-up trace in CloudWatch** to inspect this turn's answer, token usage, and duration. The session's trace list contains both turns, so you can compare them using the printed trace IDs. The evaluation result from Section 5 applies to the first answer.

In [13]:
messages = [
    *request["messages"],
    response["output"]["message"],
    {"role": "user", "content": [{"text": "What if I no longer have the original packaging?"}]},
]
turn_two_request = build_converse_request(
    SELECTED, messages, system=request["system"], max_tokens=512, effort=EFFORT,
)
with converse_observation(turn_two_request, session_id=SESSION_ID) as record_response:
    turn_two = runtime.converse(**turn_two_request)
    turn_two = record_response(turn_two)
print("".join(block["text"] for block in turn_two["output"]["message"]["content"] if "text" in block))
FOLLOWUP_TRACE_ID = turn_two["_trace"]["trace_id"]
print("Same session:", SESSION_ID)
print("First trace:", TRACE_ID)
print("Follow-up trace:", FOLLOWUP_TRACE_ID)
turn_two_spans = [doc for doc in telemetry.collector.span_documents()
                  if doc.get("traceId") == FOLLOWUP_TRACE_ID]
turn_two_records = metrics_records(turn_two_spans, backend="memory", pricing=price_observed_call)
display(pd.DataFrame(turn_two_records)[["input_tokens", "output_tokens", "cache_read_tokens", "cache_write_tokens", "cost_usd"]])
telemetry.flush(timeout_ms=5000)

if BACKEND in {"agentcore", "both"}:
    followup_query = urlencode({
        "serviceName": telemetry.service_name, "source": "agents", "traceId": FOLLOWUP_TRACE_ID,
    })
    FOLLOWUP_CLOUDWATCH_URL = (
        f"https://{REGION}.console.aws.amazon.com/cloudwatch/home?region={REGION}"
        f"#gen-ai-observability/agent-core/agent/{quote(telemetry.service_name, safe='')}"
        f"/session/{quote(SESSION_ID, safe='')}?{followup_query}"
    )
    display(Markdown(f"[Open the follow-up trace in CloudWatch]({FOLLOWUP_CLOUDWATCH_URL})"))

Without the original packaging, the return would not meet TechMart's policy requirements, so the headphones would not be eligible for return.
Same session: fundamentals-d74d6d95128550aa79ab784c9dea0482
First trace: 823c82466ca1a526266e9d9fe3e3da70
Follow-up trace: 84d60616b3da570f7101ddfd95a734e7

,input_tokens,output_tokens,cache_read_tokens,cache_write_tokens,cost_usd
0,170,41,0,0,0.00075

[Open the follow-up trace in CloudWatch](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#gen-ai-observability/agent-core/agent/fundamentals-notebook/session/fundamentals-d74d6d95128550aa79ab784c9dea0482?serviceName=fundamentals-notebook&source=agents&traceId=84d60616b3da570f7101ddfd95a734e7)

## 7. Optional: inspect the same work in Langfuse

**[Langfuse](https://langfuse.com/docs)** provides another way to view your model calls, including their prompts, answers, token usage, and estimated costs. You can send the same request's traces to both Langfuse and CloudWatch.

### Connect and run

1. Complete **Langfuse Project Setup** in your workshop walkthrough. Save the project URL and API keys in the repository's `.env` file, and configure the model definitions for cost tracking.
2. Set `OBSERVABILITY_BACKEND=both` in `.env` to send traces to both destinations. Use `langfuse` if you only want the Langfuse trace view.
3. Restart the kernel and run the notebook again through Section 6. Use the new trace and session IDs printed during this run.
4. Open your Langfuse project, choose **Tracing**, and find the printed trace ID. Open its model observation to inspect the request.

### What to inspect

| Item | What to look for |
|---|---|
| **Input and output** | The customer's question, return policy, and model answer. |
| **Usage and cost** | Input/output token counts and the estimated model cost. Cost estimates depend on the model definitions configured during setup. |
| **Duration** | The time taken by the model call. |
| **Session** | The first question and packaging follow-up grouped in one conversation. |

With `both`, compare the same trace ID in CloudWatch and Langfuse. They show records of the same model call.

**Evaluation results:** Section 5's AgentCore score and explanation remain in the notebook. They are not automatically added as scores in Langfuse.

### Optional: what changes when the agent runs remotely?

So far, the code making the Bedrock call has run inside this notebook. In an application, that code might instead run in **AgentCore Runtime** or another hosting service. The notebook sends a question to the hosted agent and waits for its answer.

The two places can record different parts of the work:

| Where recording happens | What it can show |
|---|---|
| **Notebook** | The request sent to the hosted agent and how long the notebook waited for the answer. |
| **Hosted agent** | Its internal steps, such as retrieving a policy, calling a tool, and asking a model. |
| **CloudWatch or Langfuse** | The records exported by each application, so you can inspect the full flow. |

<img src="images/telemetry-process-boundary.png" alt="The notebook and hosted agent each record their own operations and export them to an observability backend" width="850">

Enable instrumentation in the hosted agent as well as the calling application. Its internal model and tool calls are recorded where they run, then exported for inspection.

The session ID groups related conversation turns. To connect spans across the notebook and hosted agent into one trace, the applications also pass **trace context**: the IDs that identify the trace and its parent span. This lets the viewer show which remote steps belong inside the original request.

## 8. Bring this to your own project

You can use the same approach in an application outside the workshop. This example uses **Strands** to call a model and **ADOT** to record and export telemetry. The commands below are for your own project's terminal and Python environment.

### 1. Prepare CloudWatch

Follow the [AgentCore observability setup guide](https://docs.aws.amazon.com/bedrock-agentcore/latest/devguide/observability-get-started.html) to prepare the AWS account and Region:

- Enable **CloudWatch Transaction Search**, which lets you find and inspect traces.
- Allow X-Ray to deliver spans to CloudWatch Logs.
- Create an application log group and log stream.
- Give the application's AWS role permission to call the model and export telemetry.

This example sends traces to `aws/spans`. `APP_LOG_GROUP` and `APP_LOG_STREAM` identify the application log destination you create. See the [observability configuration guide](https://docs.aws.amazon.com/bedrock-agentcore/latest/devguide/observability-configure.html#observability-configure-3p) for the setup details.

### 2. Install the libraries and configure recording

Run the following in your project's virtual environment. Set the Region, model, and log destination to values available in your account, using your usual AWS profile or application role.

```bash
python -m pip install 'aws-opentelemetry-distro>=0.18.0' 'strands-agents[otel]' boto3
export AWS_REGION=us-east-1
export AWS_DEFAULT_REGION="$AWS_REGION"
export MODEL_ID=global.anthropic.claude-haiku-4-5-20251001-v1:0
export APP_LOG_GROUP=/my-app/telemetry
export APP_LOG_STREAM=application
export AGENT_OBSERVABILITY_ENABLED=true
export OTEL_PYTHON_DISTRO=aws_distro
export OTEL_PYTHON_CONFIGURATOR=aws_configurator
export OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
export OTEL_TRACES_EXPORTER=otlp
export OTEL_SERVICE_NAME=my-support-agent
export OTEL_RESOURCE_ATTRIBUTES="service.name=$OTEL_SERVICE_NAME,aws.log.group.names=$APP_LOG_GROUP"
export OTEL_EXPORTER_OTLP_LOGS_HEADERS="x-aws-log-group=$APP_LOG_GROUP,x-aws-log-stream=$APP_LOG_STREAM,x-aws-metric-namespace=bedrock-agentcore"
export AWS_GENAI_CONTENT_EXTRACTION_OPT_OUT=true
```

The settings serve these purposes:

| Settings | Purpose |
|---|---|
| `AWS_REGION`, `MODEL_ID` | Choose where the request runs and which model answers. |
| `OTEL_SERVICE_NAME` | Name the application you will find in CloudWatch. |
| `APP_LOG_GROUP`, `APP_LOG_STREAM` | Identify the application log destination. The resource attributes and log headers pass this information to the exporter. |
| `OTEL_PYTHON_DISTRO`, `OTEL_PYTHON_CONFIGURATOR` | Load ADOT's Python instrumentation and configuration. |
| `OTEL_TRACES_EXPORTER`, `OTEL_EXPORTER_OTLP_PROTOCOL` | Configure how trace records are exported. |
| `AWS_GENAI_CONTENT_EXTRACTION_OPT_OUT` | Keep prompt and answer content on spans for this example. It controls where content is recorded; it does not redact it. |

### 3. Create a small Strands application

Save the following as `agent.py`. It gives the agent a return policy, asks the customer's question, and assigns a session ID to the conversation. Strands records spans for the agent and its model calls.

```python
import os
from uuid import uuid4

from strands import Agent
from strands.models import BedrockModel

session_id = f"support-{uuid4().hex}"
agent = Agent(
    model=BedrockModel(
        model_id=os.environ["MODEL_ID"],
        region_name=os.environ["AWS_REGION"],
        max_tokens=512,
    ),
    system_prompt="Answer briefly using this policy: headphone returns require a receipt and original packaging within 30 days.",
    trace_attributes={"session.id": session_id},
    callback_handler=None,
)
print(agent("I bought headphones 14 days ago and have a receipt. Can I return them?"))
print("Session ID:", session_id)
```

### 4. Run and inspect

Launch the application with instrumentation enabled:

```bash
opentelemetry-instrument python agent.py
```

`opentelemetry-instrument` initializes recording before the application creates its agent and model client. The script prints the answer and session ID.

Open **CloudWatch GenAI Observability**, find service **my-support-agent**, and use the printed session ID to inspect the request. For further turns in the same conversation, reuse that session ID.

## 9. Finish this tracing session

Once you have finished inspecting the traces, run the last code cell to stop recording in this notebook.

`telemetry.shutdown()` sends remaining telemetry, stops the background exporters, and clears the notebook's local span collection. The output confirms that the exporters have stopped. Previously exported traces remain available in CloudWatch or Langfuse.

Restart the kernel before starting another tracing run in this notebook.

In [14]:
telemetry.shutdown()
print("Telemetry exporters stopped. Restart the kernel before initializing telemetry again.")
# Resource deletion belongs to the separate teardown workflow, after exporters have stopped.

Telemetry exporters stopped. Restart the kernel before initializing telemetry again.

## Continue to the Optimization Playbook

You've followed a two-turn conversation, inspected its traces, measured token usage and cost, and evaluated the first answer against the return policy.

Use the same approach as you improve an application: **run a task → inspect its trace → measure its cost → evaluate its answer**.

Next, open the [LOW-effort Playbook](../02-optimization-playbook/01-low-effort.ipynb) to explore model selection, prompt design, output controls, caching, and reasoning effort.

## References

- [Set up AgentCore observability](https://docs.aws.amazon.com/bedrock-agentcore/latest/devguide/observability-get-started.html)
- [Configure observability outside AgentCore Runtime](https://docs.aws.amazon.com/bedrock-agentcore/latest/devguide/observability-configure.html#observability-configure-3p)
- [CloudWatch agents view](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/agent-view.html) and [sessions view](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/session-view.html) — screenshot sources
- [AgentCore Evaluations overview](https://docs.aws.amazon.com/bedrock-agentcore/latest/devguide/evaluations.html)
- [On-demand evaluation](https://docs.aws.amazon.com/bedrock-agentcore/latest/devguide/getting-started-on-demand.html)
- [AgentCore Evaluate API](https://docs.aws.amazon.com/boto3/latest/reference/services/bedrock-agentcore/client/evaluate.html)
- [Langfuse OpenTelemetry integration](https://langfuse.com/integrations/native/opentelemetry)